[2022-07-11 10:17:50] INFO [liquibase.database] Set default schema name to public
[2022-07-11 10:17:50] INFO [liquibase.lockservice] Successfully acquired change log lock
[2022-07-11 10:17:50] INFO [liquibase.changelog] Reading resource: migrations/changeset_1.yaml
[2022-07-11 10:17:51] INFO [liquibase.changelog] Reading resource: migrations/changeset_2.yaml
[2022-07-11 10:17:51] INFO [liquibase.changelog] Reading from public.databasechangelog
[2022-07-11 10:17:51] INFO [liquibase.changelog] Tag 'yaml_tag' applied to database
[2022-07-11 10:17:52] INFO [liquibase.lockservice] Successfully released change log lock
[2022-07-11 10:17:52] SEVERE [liquibase.integration] ERROR: relation "test_yaml" already exists [Failed SQL: (0) CREATE TABLE public.test_yaml (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT test_yaml_pkey PRIMARY KEY (id))]
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Migration failed for change set migrations/changeset_1.yaml::1::zhivov_oa:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "test_yaml" already exists [Failed SQL: (0) CREATE TABLE public.test_yaml (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT test_yaml_pkey PRIMARY KEY (id))]
	at liquibase.command.CommandScope.execute(CommandScope.java:162)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:336)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:301)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:91)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Migration failed for change set migrations/changeset_1.yaml::1::zhivov_oa:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "test_yaml" already exists [Failed SQL: (0) CREATE TABLE public.test_yaml (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT test_yaml_pkey PRIMARY KEY (id))]
	at liquibase.integration.commandline.Main$1.run(Main.java:443)
	at liquibase.integration.commandline.Main$1.run(Main.java:221)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.Main.run(Main.java:221)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:33)
	at liquibase.command.CommandScope.execute(CommandScope.java:156)
	... 20 more
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/changeset_1.yaml::1::zhivov_oa:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "test_yaml" already exists [Failed SQL: (0) CREATE TABLE public.test_yaml (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT test_yaml_pkey PRIMARY KEY (id))]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:265)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:264)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2405)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1841)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.integration.commandline.Main$1.run(Main.java:397)
	... 26 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/changeset_1.yaml::1::zhivov_oa:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "test_yaml" already exists [Failed SQL: (0) CREATE TABLE public.test_yaml (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT test_yaml_pkey PRIMARY KEY (id))]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:696)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.Scope.child(Scope.java:247)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65)
	... 47 more
Caused by: liquibase.exception.DatabaseException: ERROR: relation "test_yaml" already exists [Failed SQL: (0) CREATE TABLE public.test_yaml (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT test_yaml_pkey PRIMARY KEY (id))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:434)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1296)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1278)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:661)
	... 67 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "test_yaml" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:286)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:430)
	... 72 more

[2022-07-11 10:19:57] INFO [liquibase.database] Set default schema name to public
[2022-07-11 10:19:57] INFO [liquibase.lockservice] Successfully acquired change log lock
[2022-07-11 10:19:57] INFO [liquibase.changelog] Reading resource: migrations/changeset_1.yaml
[2022-07-11 10:19:58] INFO [liquibase.changelog] Reading resource: migrations/changeset_2.yaml
[2022-07-11 10:19:58] INFO [liquibase.changelog] Creating database history table with name: public.databasechangelog
[2022-07-11 10:19:58] INFO [liquibase.changelog] Reading from public.databasechangelog
[2022-07-11 10:19:58] WARNING [liquibase.precondition] Executing changelog.yaml despite precondition failure due to onFail='WARN':
      1 preconditions failed
     changelog.yaml : Table public.test_yaml does not exist

[2022-07-11 10:19:58] INFO [liquibase.changelog] Tag 'yaml_tag' applied to database
[2022-07-11 10:19:58] INFO [liquibase.changelog] Table test_yaml created
[2022-07-11 10:19:58] INFO [liquibase.changelog] ChangeSet migrations/changeset_1.yaml::1::zhivov_oa ran successfully in 40ms
[2022-07-11 10:19:58] INFO [liquibase.changelog] Tag 'alter_table' applied to database
[2022-07-11 10:19:58] INFO [liquibase.changelog] Columns age(numeric) added to test_yaml
[2022-07-11 10:19:58] INFO [liquibase.changelog] ChangeSet migrations/changeset_2.yaml::2::zhivov_oa ran successfully in 23ms
[2022-07-11 10:19:58] INFO [liquibase.lockservice] Successfully released change log lock
